# Configuração para rodar o onlyoffice localmente
version: '2'
services:
    onlyoffice:
        image: supremotribunalfederal/onlyofficeds
        stdin_open: true
        mem_limit: 2000000000
        ports:
        - "443:443"
        environment:
        - SSL_CERTIFICATE_PATH=/certs/docker/onlyoffice.crt
        - SSL_KEY_PATH=/certs/docker/onlyoffice.key
        - SSL_DHPARAM_PATH=/certs/docker/dhparam.pem