server:
  port: 8094

spring:
  application:
    name: documents
  datasource:
    url: jdbc:h2:mem:documents;MODE=Oracle;DB_CLOSE_DELAY=-1
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none

eureka:  
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
    
flyway:
  validate-on-migrate: false

mongo:
  host: mongo
  databaseName: documento

http:
  client:
    ssl:
      trust-store: truststores/truststore.jks
      trust-store-password: changeit

onlyoffice:
  server:
    address: https://pacaembu:443