# Define a configuração para rodar esse contexto construído localmente
version: '2'
services:
  documents:
    extends:
      file: shared/compose/common.yml
      service: documents
    image: stfdigital-plataforma-documents
    links:
     - onlyoffice:docker # documents precisa acessar o onlyoffice pelo host docker para não dar erro de certificado
    depends_on:
     - mongo
     - rabbit
     - discovery
     - onlyoffice