# Define a configuração para rodar esse contexto construído localmente
version: '2'
services:
  documents:
    extends:
      file: compose/shared/common.yml
      service: documents
    depends_on:
     - mongo
     - discovery