# Extende a configuração para rodar os testes e2e.
# Deve ser rodado em combinação com shared/compose/docker-compose.e2e.base.yml
version: '2'
services:
  docker:
    environment:
     - ONLYOFFICE_PORT_443_TCP=tcp://onlyoffice:443
    depends_on:
     - onlyoffice
  onlyoffice:
    extends:
      file: shared/compose/common.yml
      service: onlyoffice
  documents:
    extends:
      file: shared/compose/common.yml
      service: documents
    image: stfdigital-plataforma-documents
    links:
     - onlyoffice:docker # documents precisa acessar o onlyoffice pelo host docker para não dar erro de certificado
    depends_on:
     - mongo
     - discovery
     - onlyoffice