# Define a configuração para rodar esse contexto construído localmente
version: '2'
services:
  documents:
    extends:
      file: shared/compose/common.yml
      service: documents
    image: stfdigital-plataforma-documents
    depends_on:
     - rabbit
     - discovery
